var  express = require('express'),
     app = express(),
 path  = require('path'),
 gapi  = require('./lib/gapi'),
 cookieParser = require('cookie-parser'),
 bodyParser = require('body-parser'),
 logger = require('morgan');

var index = require('./routes/index');
var cal = require('./routes/calendar');
var auth = require('./routes/oauthcallback');

app.set('views', __dirname + '/views');
app.set('view engine', 'pug');

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:false}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/',index);
app.use('/cal', cal);
app.use('/auth/google/callback', auth);

// Error handling automatically generated by app-generator
//is not shown

module.exports = app;